/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          rose:   "#FF4FA3",
          deep:   "#D63384",
          hot:    "#FF1493",
          light:  "#FFB3D9",
          soft:   "#FFF0F5",
          ink:    "#121212",
          muted:  "#8E8E93",
          canvas: "#F5F5F7",
          white:  "#FFFFFF",
        },
        route: {
          blue:   "#007AFF",
          green:  "#34C759",
          orange: "#FF9500",
          purple: "#AF52DE",
          red:    "#FF3B30",
          yellow: "#FFCC00",
          teal:   "#5AC8FA",
        },
        ink:    "#121212",
        body:   "#1C1C1E",
        muted:  "#8E8E93",
        canvas: "#F5F5F7",
        base:   "#F5F5F7",
        surface:"#FFFFFF",
        subtle: "#F2F2F7",
        border:          "#E5E5EA",
        "border-strong": "#D1D1D6",
        success:      "#34C759",
        "success-bg": "#E8F8E8",
        warning:      "#FF9500",
        "warning-bg": "#FFF3E0",
        info:         "#007AFF",
        "info-bg":    "#E8F0FF",
        danger:       "#FF3B30",
        "danger-bg":  "#FFE8E5",
        rose:         "#FF4FA3",
        "rose-deep":  "#D63384",
        "rose-light": "#FFB3D9",
        "rose-soft":  "#FFF0F5",
      },
      fontFamily: {
        sans: ['"Inter Tight"', '"Inter"', "-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "sans-serif"],
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.875rem" }],
        "eta": ["3.75rem", { lineHeight: "1", fontWeight: "900" }],
      },
      boxShadow: {
        sm:          "0 1px 3px rgba(0,0,0,0.05)",
        soft:        "0 4px 16px rgba(0,0,0,0.04)",
        card:        "0 1px 4px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.03)",
        "card-hover":"0 8px 32px rgba(0,0,0,0.08)",
        "card-rose": "0 4px 24px rgba(255,79,163,0.15)",
        "rose-glow": "0 0 40px rgba(255,79,163,0.35)",
        "bottom-sheet": "0 -4px 24px rgba(0,0,0,0.08)",
      },
      animation: {
        "fade-in":    "fadeIn 0.2s ease-out",
        "slide-up":   "slideUp 0.25s ease-out",
        "pulse-dot":  "pulseDot 2s ease-in-out infinite",
        "pulse-ring": "pulseRing 2s ease-in-out infinite",
        "ticker":     "ticker 0.3s ease-out",
      },
      keyframes: {
        fadeIn:    { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp:   { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        pulseDot:  { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.3" } },
        pulseRing: { "0%": { transform: "scale(1)", opacity: "1" }, "100%": { transform: "scale(1.8)", opacity: "0" } },
        ticker:    { "0%": { transform: "translateY(6px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
      },
    },
  },
  plugins: [],
};
